spring:
  application:
    name: hwapi-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_db
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis
  redis:
    port: 6379
    host: localhost
    database: 0

server:
  port: 8003
  servlet:
    context-path: /api/order
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0


dubbo:
  application:
    name: binapi-order-dubbo
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
    # ??namespace
    parameters:
      namespace: 16239c21-ac42-46bc-a4e7-690e64272f5a
    check: false
  consumer:
    check: false