server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
#      default-filters:
#        - AddResponseHeader=source, yupi
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**


dubbo:
  application:
    name: cloud-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848